[package]
name = "parseint-with-rust"
version = "1.0.0"
edition = "2018"
authors = ["Sasaki Touma (stouma915)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.8.0"